### ISSUE TITLE
Enable Experimental Vega export in Emperor plots

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/gemelli#86]
This feature, through, experimental, is helpful!

Is there any way to enable it in the current release on pip?

Here's the feature I'm thinking of from another emperor plot.
<img width="432" alt="image" src="https://github.com/biocore/gemelli/assets/10355152/20d20cf1-0d77-424a-9cad-f55d6f3be439">

**Comment by cameronmartino** [comment]
@colinbrislawn I am not sure, is that on the Emperor side or on the generation of the qza that Emperor uses to generate the plot? Happy to add it, if it is within the changes made in this repo.

**Comment by colinbrislawn** [comment]
I'm guessing it's on the Emperor side, though I'm not sure

**Comment by ElDeveloper** [comment]
Correct, this falls in the realm of Emperor 🐧.

@colinbrislawn the "problem" is that the Vega Export action doesn't currently support exporting Biplots which means that for most CTF/RPCA/PhyloRPCA plots you won't be able to use this feature. Unless you run `qiime emperor plot ... --p-ignore-pcoa-features` instead of `qiime emperor biplot ...`.

FWIW there's a ticket for this "bug": https://github.com/biocore/emperor/issues/723
